### ISSUE TITLE
Confused about usage of bucket parameter for aggregation queries

### ISSUE THREAD

**Issue by emmanuelnk** [RedisGrafana/grafana-redis-datasource#107]
Hi, great work on the plugin. I have a question though. _What is the purpose of the bucket input for aggregation?_ I feel like this is not explained well in the docs.

It was my assumption than any query that uses `TS.RANGE` uses the global time range as set by the dashboard. Aggregation is the only redis query where I see this aggregation bucket parameter. Also the input does not allow usage of grafana variables (it only accepts numbers). Why would global time range be a different value than the aggregation bucket? I assume `bucket` here means the time from now until the time you want to aggregate. 

Could you please provide information on the purpose of this parameter and how to use it effectively?

**Comment by mikhailredis** [comment]
@emmanuelnk Thank you. Bucket parameter is available for TS.RANGE and TS.MRANGE commands which support aggregation: https://oss.redislabs.com/redistimeseries/commands/#tsrangetsrevrange

Your assumption is correct, TS.RANGE and other commands use the global time range. The time bucket is used for aggregation as specified in the documentation for RedisTimeSeries. For example, instead of series with every second sample, you can use various aggregation types to return samples for the minute, hour, and so on. 

Please let me know if it's clear or you have any other questions.

Regarding using the grafana variables, I have to update for all available parameters.

**Comment by emmanuelnk** [comment]
@mikhailredis okay thanks! That clears it up! Thanks for the link to the docs. I see its essentially data binning but the term `bucket` confused me.

**Comment by mikhailredis** [comment]
@emmanuelnk Thank you for the feedback. I have updated `Bucket` to `Time Bucket`, I hope it makes it more clear.
Please let me know if there is anything else.
