### ISSUE TITLE
How to SELECT a database?

### ISSUE THREAD

**Issue by BSVogler** [RedisGrafana/grafana-redis-datasource#239]
I think selecting the database of the redis server should be an option in the configuration option. I cannot find any option for that. Is there a way to make it use a different one?
https://redis.io/commands/select

EDIT: My confusion comes from the fact that using the trailing slash notation e.g. `<url>/1` only works when you use the protocol `redis://<url>/1` in front. However this is surprising because we are using SSL, hence `redis://`should be `rediss://`

Maybe it can be improved that it always takes the `/<dbnumber>`?

**Comment by mikhailredis** [comment]
@BSVogler, thank you for the suggestion. Redis Data Source based on the Radix client, which follows Redis schema: [https://www.iana.org/assignments/uri-schemes/prov/redis](https://www.iana.org/assignments/uri-schemes/prov/redis). 

Looking at the schema, `rediss://` is supported by some clients to enable TLS  and is not a part of the standard. The Radix client controls TLS by using a special flag:
```
Apparently named by analogy to HTTPS (RFC 2818), the rediss: URI scheme (yes, two "s"es, not a typo) has been used by some clients to designate RESP over TLS. Other than the usage of TLS, the rediss: URI scheme is not known to have any differences from the redis: URI scheme.
```

Looking at the standard, `db-number` is specified as a part of the URI, and not simple notation.
I believe that using 'redis://ip:port/db-name` with TLS enabled is clear enough according to the standard.

Please let me know if it's clear. We can add an explanation in the documentation if required.

**Comment by BSVogler** [comment]
Thanks for clarifying that. It is fair that since `rediss` it is not officially part of the standard you wont't support it.

Since the connection string accepts the URI and it is clear that it a redis connection, why is `redis://ip:port/db-name` as well as `ip:port` okay,  but not `ip:port/db-name`? Whenever the protocol part is missing it could be automatically inferred.

**Comment by mikhailredis** [comment]
@BSVogler, I prefer to avoid address manipulation in the Data Source and send it as is to the Radix client.

One of the reason, the Data Source supports Standalone, Socket, Cluster and Sentinel types of connections. I have not tested `db-name` functionality in all of those modes and it will require further investigation on how adding db-name behaves.

I can think of introducing the helper, which can recommend to add `redis://` to support `db-name` so it will be transparent for the end-users.

Let me know.

**Comment by BSVogler** [comment]
I would very welcome any change which improves the UX when setting up the connection. When I tried to set up redis I initially thought that the plug-in is broken because neither the rediss protocol worked nor removing the protocol.

**Comment by mikhailredis** [comment]
@BSVogler, I appreciate the feedback and will work on improving the UX.

Please let me know if there is anything else.

**Comment by mikhailredis** [comment]
@BSVogler, I am thinking to add SELECT database functionality as a separate option and execute the `SELECT` command when opening a new connection. Let me know if you will be interested to try it.

**Comment by BSVogler** [comment]
yes, would be interested in that.

**Comment by Stono** [comment]
:wave: have been giving this plugin a go today so thought i'd share my UX feedback.  Caveat: fully appreciate it's probably just a product of the way we use redis.

We have a multi-tenant redis instance and make use of about 10 databases on it (for different domains).  I was hoping to just be able to pick the database as part of the explore or query, but I can't.  My only other option is to set up 10 datasources for each database, which seems somewhat overkill!

**Comment by slorello89** [comment]
Hi @BSVogler @Stono, sorry for the delayed response.

Let me first start off by saying that generally speaking, using numbered databases in Redis is [considered an anti-pattern](https://redis.com/blog/7-redis-worst-practices/), and their introduction is Salvatore's (the creator of Redis) [biggest design regret](https://groups.google.com/g/redis-db/c/vS5wX8X4Cjg/m/8ounBXitG4sJ) about Redis.

WRT to support for it in the data source: IMO how it works now (as part of the data source configuration) is the correct behavior. 

The command that switches between databases (`SELECT`), is a connection modifying command. After the connection runs it, it alters the state of the connection to point to the selected database. The connection will not switch back until it is instructed to do so. Since the data source pools and resues these connections, it means that you expose yourself to all sorts of undefined behaviors (misconfiguration, race conditions, etc. . .) It is a vital part of the operation of the connection to have a predictable database selected, consequentially it should be solely part of the data source's configuration. So I don't see us changing this.

The "Redis Way" to do what you are doing with databases @Stono - would be to namespace your keys to each domain - e.g.

`domain-1:hash:12345`
`domain-2:hash:43216`

**Comment by Stono** [comment]
It might be a design regret but it's a supported feature, and works well for us to isolate applications on multi tenant instances.  

We used to be in redis/0 with key prefixes, but people ended up forgetting, using the same keys, etc.  Having isolated databases per application stops people using redis as a means of sharing data between microservices, which is something we don't encourage.   From an observability and alerting perspective, it's far easier to see things like usage by application when they're isolated by db, rather than by key prefix.  

We've no intent on changing this strategy either :D so I'll likely look to fork this and try and implement the changes for my admittedly sufficiently unique use case, as it's most of the way towards what I need!

Ta

**Comment by slorello89** [comment]
Sounds good - data source is under an Apache-2.0 license, Grafana supports privately signed/unsigned plugins so easy enough to fork and do your own thing - the dev guide is available [here](https://redisgrafana.github.io/development/redis-datasource/) - I found it quite helpful.

**Comment by BSVogler** [comment]
> Let me first start off by saying that generally speaking, using numbered databases in Redis is [considered an anti-pattern](https://redis.com/blog/7-redis-worst-practices/), and their introduction is Salvatore's (the creator of Redis) [biggest design regret](https://groups.google.com/g/redis-db/c/vS5wX8X4Cjg/m/8ounBXitG4sJ) about Redis.

I was aware of it being an antipattern but Salvatore overlooks some use-cases. Let me share my experience to explain why the support for multiple dbs is a good feature. We use it to split one instance to serve multiple non-production environments. This way the key space operates in isolation. 
Prefixing can solve this but it expects that every client command in your application logic follows the prefix and you can easily bypass it. I. e. Some third-party libs that use redis would be colliding in key space then. Getting more instances per environment is not cost-efficient and wastes resources.

I have not used the redis with grafana in a while but I hope to go back to it soon and check it out. Thanks.
