### ISSUE TITLE
Simple way to query all streams and retrieve length of stream

### ISSUE THREAD

**Issue by ilana-makover** [RedisGrafana/grafana-redis-datasource#291]
Hi, I have a redis connection that has multiple redis streams. For each stream, I would like to retrieve the length of the stream. 
Instead of querying redis for each stream name and asking for the length, is there an easier way to do this?
Currently I have 50+ queries. 

Thank you in advance.

**Comment by slorello89** [comment]
Hi @ilana-makover There's currently not a variadic way to call `XLEN`

You could potentially run a lua script via the CLI input and collate everything - I don't think that will parse particularly nicely because I believe everything is returned as a single sting - there's also a complication in that will be rather difficult to achieve in a cluster as the keys you are accessing might be on different shards.

**Comment by slorello89** [comment]
closing as I think the question has been answered - feel free to open if there's anything else.
