### ISSUE TITLE
Is it possible to return multiple options when querying an array of json, instead of a single stringified array, in the Grafana dashboard?

### ISSUE THREAD

**Issue by sam30606** [RedisGrafana/grafana-redis-datasource#311]
## Summary

Hi, After many times attempts, I've noticed that when querying an array of JSON, it returns a stringified array.
However, this format is not very convenient when using Grafana dashboards.

Is it possible to return multiple options in a format that is more suitable for variables in the dashboard?

- Inconvenient one
![image](https://github.com/RedisGrafana/grafana-redis-datasource/assets/61706675/b5ece3e0-b52c-42b0-8b4f-1763cc9bccee)

- The one that I wish
![image](https://github.com/RedisGrafana/grafana-redis-datasource/assets/61706675/b4141a5d-ba1a-49c9-a918-85ea4a0559bc)

**Comment by slorello89** [comment]
Hi @sam30606 - so when querying a variable, it just issues a raw query to Redis, the response you are getting from that query is the response from Redis, Redis responds with a bulk string to `JSON.GET`, so that's what you get back. When you do an LRANGE on the other hand, you get an array of bulk strings (they aren't encoded as numbers either). So here again the plugin is working as expected.

**Comment by sam30606** [comment]
Thanks! 
So, is the difference about how Redis responds to affect the present in Grafana dashboard?
